[package]
name = "short-url-srv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.7" }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0" , features = ["derive"]}
sqlx = { version = "0.7", features = [ "runtime-tokio","mysql", "time" ] }
tracing = "0.1"
bcrypt = "0.15"
rand = "0.8"
log = { version = "0.4", features = ["std", "serde"] }
tracing-subscriber = "0.3.18"
