http:
  port: 0.0.0.0:10240

log:
  file:
    enable: true
    level: info
    filepath: ./logs
    filename: app.log
  stdout:
    enable: true
    level: info

database:
  mysql:
    dsn: mysql://root:admin123@localhost:3306/short_url_srv
    max_conns: 128
